# Generated by Django 5.1.3 on 2024-12-11 20:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0002_expense_tenant'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='expense',
            name='tenant',
        ),
    ]
