# Generated by Django 5.1.3 on 2024-12-10 10:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('properties', '0001_initial'),
        ('tenants', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ParkingSpace',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('identifier', models.CharField(help_text='Unique identifier for the parking space (e.g., Spot A1, Garage #3).', max_length=50, unique=True)),
                ('size', models.CharField(help_text='Size description of the parking space (e.g., Compact, Standard, Large).', max_length=50)),
                ('is_covered', models.BooleanField(default=False, help_text='Indicates if the parking space is covered.')),
                ('monthly_rent', models.DecimalField(decimal_places=2, help_text='Monthly rent amount for the parking space.', max_digits=10)),
                ('status', models.CharField(choices=[('Available', 'Available'), ('Reserved', 'Reserved'), ('Occupied', 'Occupied')], default='Available', help_text='Current status of the parking space.', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('property', models.ForeignKey(help_text='The property to which this parking space belongs.', on_delete=django.db.models.deletion.CASCADE, related_name='parking_spaces', to='properties.property')),
                ('reserved_by', models.ForeignKey(blank=True, help_text='The user who has reserved this parking space (if applicable).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reserved_parking_spaces', to=settings.AUTH_USER_MODEL)),
                ('tenant', models.ForeignKey(blank=True, help_text='The tenant who has rented this parking space, if any.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='parking_spaces', to='tenants.tenant')),
            ],
            options={
                'verbose_name': 'Parking Space',
                'verbose_name_plural': 'Parking Spaces',
                'unique_together': {('property', 'identifier')},
            },
        ),
    ]
