# Generated by Django 5.1.3 on 2024-12-10 11:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parking_api', '0002_remove_parkingspace_reserved_by'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='parkingspace',
            name='owner',
            field=models.ForeignKey(default=2, help_text='The owner of this parking space.', on_delete=django.db.models.deletion.CASCADE, related_name='parking_spaces', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
