# Generated by Django 5.1.3 on 2024-12-04 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tenant',
            name='contact_info',
            field=models.TextField(),
        ),
    ]
