# Generated by Django 5.1.3 on 2024-12-04 20:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0002_alter_tenant_contact_info'),
    ]

    operations = [
        migrations.AddField(
            model_name='tenant',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='tenant_photos/'),
        ),
    ]
